name: Build and Push to ECR

on:
  push:
    branches:
        - main  # Run the workflow on changes pushed to the master branch
        - dev   # Run the workflow on changes pushed to the dev branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      # Use GitHub Secrets to securely provide AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1  # The AWS region where the ECR repository is located

      # Step 3: Log in to Amazon ECR
      # Authenticate Docker CLI with your ECR registry
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 930354804502.dkr.ecr.eu-north-1.amazonaws.com

      # Step 4: Build the Docker image and tag it
      # Tag the image with 'latest' and a dynamic tag (branch name and commit SHA)
      - name: Build Docker image
        run: |
          docker build -t ayalabar-app:latest .
          docker tag ayalabar-app:latest 930354804502.dkr.ecr.eu-north-1.amazonaws.com/ayalabar-app:latest
          docker tag ayalabar-app:latest 930354804502.dkr.ecr.eu-north-1.amazonaws.com/ayalabar-app-${{ github.ref_name }}-${{ github.sha }}

      # Step 5: Push the Docker image to ECR
      # Push the 'latest' tag and the dynamic tag to the ECR repository
      - name: Push Docker image to ECR
        run: |
          docker push 930354804502.dkr.ecr.eu-north-1.amazonaws.com/ayalabar-app:latest
          docker push 930354804502.dkr.ecr.eu-north-1.amazonaws.com/ayalabar-app-${{ github.ref_name }}-${{ github.sha }}
